//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.comarch.mobile.ndg.Languages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.comarch.mobile.ndg.Languages.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nokia Data Gathering.
        /// </summary>
        public static string applicationTitle {
            get {
                return ResourceManager.GetString("applicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download list, check server URL address..
        /// </summary>
        public static string checkForNewSurveyList_DownloadFailed {
            get {
                return ResourceManager.GetString("checkForNewSurveyList_DownloadFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading list of surveys....
        /// </summary>
        public static string checkForNewSurveyList_Downloading {
            get {
                return ResourceManager.GetString("checkForNewSurveyList_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are {0} new surveys..
        /// </summary>
        public static string checkForNewSurveyList_ManyNewSurveys {
            get {
                return ResourceManager.GetString("checkForNewSurveyList_ManyNewSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is one new survey..
        /// </summary>
        public static string checkForNewSurveyList_OneNewSurvey {
            get {
                return ResourceManager.GetString("checkForNewSurveyList_OneNewSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error..
        /// </summary>
        public static string checkForNewSurveyList_ServerError {
            get {
                return ResourceManager.GetString("checkForNewSurveyList_ServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t download list, server sent incomplete response..
        /// </summary>
        public static string checkForNewSurveyList_ServerIncompleteResponse {
            get {
                return ResourceManager.GetString("checkForNewSurveyList_ServerIncompleteResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server not found, check your internet connection and server URL address and then try again..
        /// </summary>
        public static string checkForNewSurveyList_ServerNotFound {
            get {
                return ResourceManager.GetString("checkForNewSurveyList_ServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show list of new surveys?.
        /// </summary>
        public static string checkForNewSurveyList_WantDownload {
            get {
                return ResourceManager.GetString("checkForNewSurveyList_WantDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not found any new surveys..
        /// </summary>
        public static string checkForNewSurveyList_ZeroNewSurvey {
            get {
                return ResourceManager.GetString("checkForNewSurveyList_ZeroNewSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to add additional copies of category?.
        /// </summary>
        public static string conditionCategoryControl_MessageBoxMessage {
            get {
                return ResourceManager.GetString("conditionCategoryControl_MessageBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add categories.
        /// </summary>
        public static string conditionCategoryControl_MessageBoxTitle {
            get {
                return ResourceManager.GetString("conditionCategoryControl_MessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are more copies of category then currently selected. Do you want to limit copies to selected amount?.
        /// </summary>
        public static string conditionCategoryControl_RemoveMessageBoxMessage {
            get {
                return ResourceManager.GetString("conditionCategoryControl_RemoveMessageBoxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove categories.
        /// </summary>
        public static string conditionCategoryControl_RemoveMessageBoxTitle {
            get {
                return ResourceManager.GetString("conditionCategoryControl_RemoveMessageBoxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pick date before {0}.
        /// </summary>
        public static string dateQuestion_MaxDateReached {
            get {
                return ResourceManager.GetString("dateQuestion_MaxDateReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must pick date after {0}.
        /// </summary>
        public static string dateQuestion_MinDateReached {
            get {
                return ResourceManager.GetString("dateQuestion_MinDateReached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t confirm download..
        /// </summary>
        public static string downloadNewSurveys_CantConfirm {
            get {
                return ResourceManager.GetString("downloadNewSurveys_CantConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t download surveys..
        /// </summary>
        public static string downloadNewSurveys_CantDownloading {
            get {
                return ResourceManager.GetString("downloadNewSurveys_CantDownloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading new surveys....
        /// </summary>
        public static string downloadNewSurveys_Downloading {
            get {
                return ResourceManager.GetString("downloadNewSurveys_Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading completed..
        /// </summary>
        public static string downloadNewSurveys_DownloadingCompleted {
            get {
                return ResourceManager.GetString("downloadNewSurveys_DownloadingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There were more surveys. Please refresh your list and try again..
        /// </summary>
        public static string downloadNewSurveys_MoreSurveys {
            get {
                return ResourceManager.GetString("downloadNewSurveys_MoreSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with saving new surveys, probably you don&apos;t have enough space to save surveys..
        /// </summary>
        public static string downloadNewSurveys_SavingProblem {
            get {
                return ResourceManager.GetString("downloadNewSurveys_SavingProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t download surveys, server sent wrong response..
        /// </summary>
        public static string downloadNewSurveys_WrongResponse {
            get {
                return ResourceManager.GetString("downloadNewSurveys_WrongResponse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to close application?.
        /// </summary>
        public static string enableEncryptionPage_closeQuestion {
            get {
                return ResourceManager.GetString("enableEncryptionPage_closeQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty..
        /// </summary>
        public static string enableEncryptionPage_emptyError {
            get {
                return ResourceManager.GetString("enableEncryptionPage_emptyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        public static string enableEncryptionPage_offAnswer {
            get {
                return ResourceManager.GetString("enableEncryptionPage_offAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        public static string enableEncryptionPage_onAnswer {
            get {
                return ResourceManager.GetString("enableEncryptionPage_onAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption password:.
        /// </summary>
        public static string enableEncryptionPage_passwordHeader {
            get {
                return ResourceManager.GetString("enableEncryptionPage_passwordHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I want encrypt to be:.
        /// </summary>
        public static string enableEncryptionPage_question {
            get {
                return ResourceManager.GetString("enableEncryptionPage_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encryption.
        /// </summary>
        public static string enableEncryptionPage_title {
            get {
                return ResourceManager.GetString("enableEncryptionPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is incorrect. Try again..
        /// </summary>
        public static string encryptionPasswordPage_error {
            get {
                return ResourceManager.GetString("encryptionPasswordPage_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter encryption password:.
        /// </summary>
        public static string encryptionPasswordPage_question {
            get {
                return ResourceManager.GetString("encryptionPasswordPage_question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to encryption.
        /// </summary>
        public static string encryptionPasswordPage_title {
            get {
                return ResourceManager.GetString("encryptionPasswordPage_title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition.
        /// </summary>
        public static string fillingSurveyPage_Condition {
            get {
                return ResourceManager.GetString("fillingSurveyPage_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter result title:.
        /// </summary>
        public static string fillingSurveyPage_enterResultTitleDialog {
            get {
                return ResourceManager.GetString("fillingSurveyPage_enterResultTitleDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not retrieve GPS position. Result was saved without current location..
        /// </summary>
        public static string fillingSurveyPage_FailedGPSSave {
            get {
                return ResourceManager.GetString("fillingSurveyPage_FailedGPSSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all answers are correct, only correct answers will be saved..
        /// </summary>
        public static string fillingSurveyPage_isCorrectDialogMessage {
            get {
                return ResourceManager.GetString("fillingSurveyPage_isCorrectDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to save result.
        /// </summary>
        public static string fillingSurveyPage_OnSaveResultTitle {
            get {
                return ResourceManager.GetString("fillingSurveyPage_OnSaveResultTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opening result....
        /// </summary>
        public static string fillingSurveyPage_opaningMessage {
            get {
                return ResourceManager.GetString("fillingSurveyPage_opaningMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result title can&apos;t be empty, try again..
        /// </summary>
        public static string fillingSurveyPage_saveDialogError {
            get {
                return ResourceManager.GetString("fillingSurveyPage_saveDialogError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to save last changes?.
        /// </summary>
        public static string fillingSurveyPage_saveQuestion {
            get {
                return ResourceManager.GetString("fillingSurveyPage_saveQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving result....
        /// </summary>
        public static string fillingSurveyPage_savingMessage {
            get {
                return ResourceManager.GetString("fillingSurveyPage_savingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Result successfully saved..
        /// </summary>
        public static string fillingSurveyPage_successSaveDialog {
            get {
                return ResourceManager.GetString("fillingSurveyPage_successSaveDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show all.
        /// </summary>
        public static string filterListPage_ShowAllOnMap {
            get {
                return ResourceManager.GetString("filterListPage_ShowAllOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image does not exist..
        /// </summary>
        public static string imageQuestion_ImageIsNull {
            get {
                return ResourceManager.GetString("imageQuestion_ImageIsNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Images: {0}/{1}.
        /// </summary>
        public static string imageQuestion_Images {
            get {
                return ResourceManager.GetString("imageQuestion_Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse images.
        /// </summary>
        public static string imageQuestionControl_BrowseImagesButton {
            get {
                return ResourceManager.GetString("imageQuestionControl_BrowseImagesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete.
        /// </summary>
        public static string imageQuestionControl_DeleteImagesButton {
            get {
                return ResourceManager.GetString("imageQuestionControl_DeleteImagesButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have reached max image capacity in this question..
        /// </summary>
        public static string imageQuestionControl_MaxImageCapacity {
            get {
                return ResourceManager.GetString("imageQuestionControl_MaxImageCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to take photo.
        /// </summary>
        public static string imageQuestionControl_TakePhotoButton {
            get {
                return ResourceManager.GetString("imageQuestionControl_TakePhotoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string indicatorStyle_BusyText {
            get {
                return ResourceManager.GetString("indicatorStyle_BusyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all.
        /// </summary>
        public static string listOfNewSurveysPage_DownloadAll {
            get {
                return ResourceManager.GetString("listOfNewSurveysPage_DownloadAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string listOfNewSurveysPage_DownloadingProgress {
            get {
                return ResourceManager.GetString("listOfNewSurveysPage_DownloadingProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to download..
        /// </summary>
        public static string listOfNewSurveysPage_NothingDownload {
            get {
                return ResourceManager.GetString("listOfNewSurveysPage_NothingDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new surveys.
        /// </summary>
        public static string listOfNewSurveysPage_PageTitle {
            get {
                return ResourceManager.GetString("listOfNewSurveysPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list.
        /// </summary>
        public static string listOfNewSurveysPage_RefreshList {
            get {
                return ResourceManager.GetString("listOfNewSurveysPage_RefreshList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is too late to interrupt downloading..
        /// </summary>
        public static string listOfNewSurveysPage_TooLateInterrupt {
            get {
                return ResourceManager.GetString("listOfNewSurveysPage_TooLateInterrupt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download all.
        /// </summary>
        public static string listOfNewSurveysPageAppBarr_Download {
            get {
                return ResourceManager.GetString("listOfNewSurveysPageAppBarr_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh list.
        /// </summary>
        public static string listOfNewSurveysPageAppBarr_Refresh {
            get {
                return ResourceManager.GetString("listOfNewSurveysPageAppBarr_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list of surveys.
        /// </summary>
        public static string listOfSurveysPage_PageTitle {
            get {
                return ResourceManager.GetString("listOfSurveysPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All surveys.
        /// </summary>
        public static string listOfSurveysPageAppBar_AllSurveys {
            get {
                return ResourceManager.GetString("listOfSurveysPageAppBar_AllSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for new Surveys.
        /// </summary>
        public static string listOfSurveysPageAppBar_CheckNewSurveys {
            get {
                return ResourceManager.GetString("listOfSurveysPageAppBar_CheckNewSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check for update.
        /// </summary>
        public static string listOfSurveysPageAppBar_CheckUpdate {
            get {
                return ResourceManager.GetString("listOfSurveysPageAppBar_CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorites.
        /// </summary>
        public static string listOfSurveysPageAppBar_FavoriteSurveys {
            get {
                return ResourceManager.GetString("listOfSurveysPageAppBar_FavoriteSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string listOfSurveysPageAppBar_Filter {
            get {
                return ResourceManager.GetString("listOfSurveysPageAppBar_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string listOfSurveysPageAppBar_Settings {
            get {
                return ResourceManager.GetString("listOfSurveysPageAppBar_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test connection.
        /// </summary>
        public static string listOfSurveysPageAppBar_TestConnection {
            get {
                return ResourceManager.GetString("listOfSurveysPageAppBar_TestConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string messageBox_Cancel {
            get {
                return ResourceManager.GetString("messageBox_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string messageBox_Download {
            get {
                return ResourceManager.GetString("messageBox_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string messageBox_No {
            get {
                return ResourceManager.GetString("messageBox_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string messageBox_OK {
            get {
                return ResourceManager.GetString("messageBox_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show.
        /// </summary>
        public static string messageBox_Show {
            get {
                return ResourceManager.GetString("messageBox_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string messageBox_Yes {
            get {
                return ResourceManager.GetString("messageBox_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection..
        /// </summary>
        public static string operationsOnRegistration_CheckConnection {
            get {
                return ResourceManager.GetString("operationsOnRegistration_CheckConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check your internet connection or server address..
        /// </summary>
        public static string operationsOnRegistration_CheckConnectionServerAddress {
            get {
                return ResourceManager.GetString("operationsOnRegistration_CheckConnectionServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection Problem.
        /// </summary>
        public static string operationsOnRegistration_ConnectionProblem {
            get {
                return ResourceManager.GetString("operationsOnRegistration_ConnectionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can contain maximum {0} characters..
        /// </summary>
        public static string operationsOnRegistration_ContainMaximum {
            get {
                return ResourceManager.GetString("operationsOnRegistration_ContainMaximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must contain minimum {0} characters..
        /// </summary>
        public static string operationsOnRegistration_ContainMinimum {
            get {
                return ResourceManager.GetString("operationsOnRegistration_ContainMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number is not valid or IMEI already exists..
        /// </summary>
        public static string operationsOnRegistration_PhoneNotValidIMEIExist {
            get {
                return ResourceManager.GetString("operationsOnRegistration_PhoneNotValidIMEIExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string operationsOnRegistration_ProcessingBarInformation {
            get {
                return ResourceManager.GetString("operationsOnRegistration_ProcessingBarInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IMEI was registered successfully..
        /// </summary>
        public static string operationsOnRegistration_RegistratedSuccessfully {
            get {
                return ResourceManager.GetString("operationsOnRegistration_RegistratedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Failed.
        /// </summary>
        public static string operationsOnRegistration_RegistrationFailed {
            get {
                return ResourceManager.GetString("operationsOnRegistration_RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Success.
        /// </summary>
        public static string operationsOnRegistration_RegistrationSuccess {
            get {
                return ResourceManager.GetString("operationsOnRegistration_RegistrationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is not responding, check your internet connection..
        /// </summary>
        public static string operationsOnRegistration_ServerNotResponding {
            get {
                return ResourceManager.GetString("operationsOnRegistration_ServerNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set server address..
        /// </summary>
        public static string operationsOnRegistration_SetServerAddress {
            get {
                return ResourceManager.GetString("operationsOnRegistration_SetServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make sure your server address is valid..
        /// </summary>
        public static string operationsOnRegistration_ValidServerAddress {
            get {
                return ResourceManager.GetString("operationsOnRegistration_ValidServerAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Working....
        /// </summary>
        public static string processingBar_Working {
            get {
                return ResourceManager.GetString("processingBar_Working", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to registration.
        /// </summary>
        public static string registrationPage_PageTitle {
            get {
                return ResourceManager.GetString("registrationPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string registrationPage_RegisterButton {
            get {
                return ResourceManager.GetString("registrationPage_RegisterButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your IMEI:.
        /// </summary>
        public static string registrationPage_TitleIMEI {
            get {
                return ResourceManager.GetString("registrationPage_TitleIMEI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your phone number:.
        /// </summary>
        public static string registrationPage_TitlePhoneNumber {
            get {
                return ResourceManager.GetString("registrationPage_TitlePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Address:.
        /// </summary>
        public static string registrationPage_TitleServerUrl {
            get {
                return ResourceManager.GetString("registrationPage_TitleServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All surveys.
        /// </summary>
        public static string resultsFilter_AllSurveys {
            get {
                return ResourceManager.GetString("resultsFilter_AllSurveys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to after.
        /// </summary>
        public static string resultsFilter_DateTypeAfter {
            get {
                return ResourceManager.GetString("resultsFilter_DateTypeAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at.
        /// </summary>
        public static string resultsFilter_DateTypeAt {
            get {
                return ResourceManager.GetString("resultsFilter_DateTypeAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to before.
        /// </summary>
        public static string resultsFilter_DateTypeBefore {
            get {
                return ResourceManager.GetString("resultsFilter_DateTypeBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to between.
        /// </summary>
        public static string resultsFilter_DateTypeBetween {
            get {
                return ResourceManager.GetString("resultsFilter_DateTypeBetween", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location services must be enabled on your phone..
        /// </summary>
        public static string resultsFilter_LocationDisable {
            get {
                return ResourceManager.GetString("resultsFilter_LocationDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None saved GPS position.
        /// </summary>
        public static string resultsFilter_NoneSavedGPSPosition {
            get {
                return ResourceManager.GetString("resultsFilter_NoneSavedGPSPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Searching....
        /// </summary>
        public static string resultsFilter_Searching {
            get {
                return ResourceManager.GetString("resultsFilter_Searching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to and.
        /// </summary>
        public static string resultsFilterPage_And {
            get {
                return ResourceManager.GetString("resultsFilterPage_And", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter by date.
        /// </summary>
        public static string resultsFilterPage_FilterByDate {
            get {
                return ResourceManager.GetString("resultsFilterPage_FilterByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter by location.
        /// </summary>
        public static string resultsFilterPage_FilterByLocation {
            get {
                return ResourceManager.GetString("resultsFilterPage_FilterByLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to filter by survey.
        /// </summary>
        public static string resultsFilterPage_FilterBySurvey {
            get {
                return ResourceManager.GetString("resultsFilterPage_FilterBySurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to survey page.
        /// </summary>
        public static string resultsFilterPage_GoToSurveyPage {
            get {
                return ResourceManager.GetString("resultsFilterPage_GoToSurveyPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude:.
        /// </summary>
        public static string resultsFilterPage_Latitude {
            get {
                return ResourceManager.GetString("resultsFilterPage_Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude:.
        /// </summary>
        public static string resultsFilterPage_Longitude {
            get {
                return ResourceManager.GetString("resultsFilterPage_Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no results matching your query..
        /// </summary>
        public static string resultsFilterPage_NoResultsMatch {
            get {
                return ResourceManager.GetString("resultsFilterPage_NoResultsMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to browse results.
        /// </summary>
        public static string resultsFilterPage_PageTitle {
            get {
                return ResourceManager.GetString("resultsFilterPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius:.
        /// </summary>
        public static string resultsFilterPage_Radius {
            get {
                return ResourceManager.GetString("resultsFilterPage_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to remove selected.
        /// </summary>
        public static string resultsFilterPage_RemoveSelectedButton {
            get {
                return ResourceManager.GetString("resultsFilterPage_RemoveSelectedButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in:.
        /// </summary>
        public static string resultsFilterPage_SearchIn {
            get {
                return ResourceManager.GetString("resultsFilterPage_SearchIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select surveys created.
        /// </summary>
        public static string resultsFilterPage_SelectCreated {
            get {
                return ResourceManager.GetString("resultsFilterPage_SelectCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show on map.
        /// </summary>
        public static string resultsFilterPage_ShowOnMap {
            get {
                return ResourceManager.GetString("resultsFilterPage_ShowOnMap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply.
        /// </summary>
        public static string resultsFilterPageAppBar_Apply {
            get {
                return ResourceManager.GetString("resultsFilterPageAppBar_Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string resultsFilterPageAppBar_Edit {
            get {
                return ResourceManager.GetString("resultsFilterPageAppBar_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Me.
        /// </summary>
        public static string resultsFilterPageAppBar_Me {
            get {
                return ResourceManager.GetString("resultsFilterPageAppBar_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking new surveys at start.
        /// </summary>
        public static string settings_AutoCheckNewSurvey {
            get {
                return ResourceManager.GetString("settings_AutoCheckNewSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string settings_Custom {
            get {
                return ResourceManager.GetString("settings_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date format.
        /// </summary>
        public static string settings_DateFormat {
            get {
                return ResourceManager.GetString("settings_DateFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone theme.
        /// </summary>
        public static string settings_Default {
            get {
                return ResourceManager.GetString("settings_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete settings.
        /// </summary>
        public static string settings_deleteSettings {
            get {
                return ResourceManager.GetString("settings_deleteSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting settings will remove all stored settings including server URI and switch view to registration page !.
        /// </summary>
        public static string settings_deleteSettingsDialogMessage {
            get {
                return ResourceManager.GetString("settings_deleteSettingsDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font size.
        /// </summary>
        public static string settings_FontSize {
            get {
                return ResourceManager.GetString("settings_FontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPS Configuration.
        /// </summary>
        public static string settings_GPS {
            get {
                return ResourceManager.GetString("settings_GPS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Contrast.
        /// </summary>
        public static string settings_HighContrast {
            get {
                return ResourceManager.GetString("settings_HighContrast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot load settings. Please restart application..
        /// </summary>
        public static string settings_IsolatedStorageFailed {
            get {
                return ResourceManager.GetString("settings_IsolatedStorageFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string settings_Language {
            get {
                return ResourceManager.GetString("settings_Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        public static string settings_Large {
            get {
                return ResourceManager.GetString("settings_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string settings_Medium {
            get {
                return ResourceManager.GetString("settings_Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default.
        /// </summary>
        public static string settings_NDG {
            get {
                return ResourceManager.GetString("settings_NDG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Green.
        /// </summary>
        public static string settings_OtherTheme {
            get {
                return ResourceManager.GetString("settings_OtherTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone language.
        /// </summary>
        public static string settings_PhoneLanguage {
            get {
                return ResourceManager.GetString("settings_PhoneLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick a photo resolution.
        /// </summary>
        public static string settings_PhotoResolution {
            get {
                return ResourceManager.GetString("settings_PhotoResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot save new settings..
        /// </summary>
        public static string settings_SaveFailed {
            get {
                return ResourceManager.GetString("settings_SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nothing to save..
        /// </summary>
        public static string settings_SaveNothing {
            get {
                return ResourceManager.GetString("settings_SaveNothing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All settings have been deleted..
        /// </summary>
        public static string settings_settingsDeleted {
            get {
                return ResourceManager.GetString("settings_settingsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        public static string settings_Small {
            get {
                return ResourceManager.GetString("settings_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string settings_Theme {
            get {
                return ResourceManager.GetString("settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not valid. Please insert number in range {0}-{1}.
        /// </summary>
        public static string settingsPage_InvalidCustomValue {
            get {
                return ResourceManager.GetString("settingsPage_InvalidCustomValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string settingsPage_PageTitle {
            get {
                return ResourceManager.GetString("settingsPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to back to edit.
        /// </summary>
        public static string surveyPage_contextMenuBackToEdit {
            get {
                return ResourceManager.GetString("surveyPage_contextMenuBackToEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to delete result.
        /// </summary>
        public static string surveyPage_contextMenuDeleteItem {
            get {
                return ResourceManager.GetString("surveyPage_contextMenuDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit result.
        /// </summary>
        public static string surveyPage_contextMenuEditItem {
            get {
                return ResourceManager.GetString("surveyPage_contextMenuEditItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to send result.
        /// </summary>
        public static string surveyPage_contextMenuSendItem {
            get {
                return ResourceManager.GetString("surveyPage_contextMenuSendItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show result.
        /// </summary>
        public static string surveyPage_contextMenuShowItem {
            get {
                return ResourceManager.GetString("surveyPage_contextMenuShowItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete this result!.
        /// </summary>
        public static string surveyPage_deleteResultError {
            get {
                return ResourceManager.GetString("surveyPage_deleteResultError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete this result?.
        /// </summary>
        public static string surveyPage_deleteResultQuestionMessage {
            get {
                return ResourceManager.GetString("surveyPage_deleteResultQuestionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete result.
        /// </summary>
        public static string surveyPage_deleteResultQuestionTitle {
            get {
                return ResourceManager.GetString("surveyPage_deleteResultQuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want delete survey and all results?.
        /// </summary>
        public static string surveyPage_deleteSurveyDialogMessage {
            get {
                return ResourceManager.GetString("surveyPage_deleteSurveyDialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete survey.
        /// </summary>
        public static string surveyPage_deleteSurveyDialogTitle {
            get {
                return ResourceManager.GetString("surveyPage_deleteSurveyDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete this survey!.
        /// </summary>
        public static string surveyPage_deleteSurveyError {
            get {
                return ResourceManager.GetString("surveyPage_deleteSurveyError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved results:.
        /// </summary>
        public static string surveyPage_resultsListtitle {
            get {
                return ResourceManager.GetString("surveyPage_resultsListtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey ID:.
        /// </summary>
        public static string surveyPage_SurveyID {
            get {
                return ResourceManager.GetString("surveyPage_SurveyID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add to favorite.
        /// </summary>
        public static string surveyPageAppBar_AddToFavorite {
            get {
                return ResourceManager.GetString("surveyPageAppBar_AddToFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete survey.
        /// </summary>
        public static string surveyPageAppBar_Delete {
            get {
                return ResourceManager.GetString("surveyPageAppBar_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to new result.
        /// </summary>
        public static string surveyPageAppBar_NewResult {
            get {
                return ResourceManager.GetString("surveyPageAppBar_NewResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove from favorite.
        /// </summary>
        public static string surveyPageAppBar_RemoveFromFavorite {
            get {
                return ResourceManager.GetString("surveyPageAppBar_RemoveFromFavorite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending completed..
        /// </summary>
        public static string surveyViewModel_sendingCompleted {
            get {
                return ResourceManager.GetString("surveyViewModel_sendingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending result, please wait...
        /// </summary>
        public static string surveyViewModel_sendingProgressTitle {
            get {
                return ResourceManager.GetString("surveyViewModel_sendingProgressTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send this result, probably result  is too large. Contact the server administrator to resolve this problem or change application settings and try send smaller result..
        /// </summary>
        public static string surveyViewModel_serverError {
            get {
                return ResourceManager.GetString("surveyViewModel_serverError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot send this result, check your internet connection and try again..
        /// </summary>
        public static string surveyViewModel_unknownError {
            get {
                return ResourceManager.GetString("surveyViewModel_unknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server is up and running..
        /// </summary>
        public static string testConnection_ServerOk {
            get {
                return ResourceManager.GetString("testConnection_ServerOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to test connection.
        /// </summary>
        public static string testConnectionPage_PageTitle {
            get {
                return ResourceManager.GetString("testConnectionPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updates.
        /// </summary>
        public static string updatesPage_PageTitle {
            get {
                return ResourceManager.GetString("updatesPage_PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field cannot be empty..
        /// </summary>
        public static string validationRules_LengthEmptyMessage {
            get {
                return ResourceManager.GetString("validationRules_LengthEmptyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field can contain only {0} characters..
        /// </summary>
        public static string validationRules_LengthMaxMessage {
            get {
                return ResourceManager.GetString("validationRules_LengthMaxMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field must contain at least {0} characters..
        /// </summary>
        public static string validationRules_LengthMinMessage {
            get {
                return ResourceManager.GetString("validationRules_LengthMinMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max field value is {0}.
        /// </summary>
        public static string validationRules_MaxReachedMessage {
            get {
                return ResourceManager.GetString("validationRules_MaxReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min field value is {0}.
        /// </summary>
        public static string validationRules_MinReachedMessage {
            get {
                return ResourceManager.GetString("validationRules_MinReachedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not valid..
        /// </summary>
        public static string validationRules_RegexValueNotValid {
            get {
                return ResourceManager.GetString("validationRules_RegexValueNotValid", resourceCulture);
            }
        }
    }
}
